AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  ItineraryTextFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: itinerary_text/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
      - Statement:
        - Sid: InvokeSageMaker
          Effect: Allow
          Action:
          - sagemaker:InvokeEndpoint
          Resource: '*'
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT: j2-mid
      Events:
        InvokeTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /text
            Method: post
            RestApiId: !Ref ServerlessRestApi
  ItineraryImageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: itinerary_image/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
      - Statement:
        - Sid: InvokeSageMaker
          Effect: Allow
          Action:
          - sagemaker:InvokeEndpoint
          Resource: '*'
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT: sdxl-jumpstart-2023-09-22-04-39-33-416
      Events:
        InvokeTest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /image
            Method: post
            RestApiId: !Ref ServerlessRestApi
    Metadata:
      BuildMethod: makefile
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ItineraryTextFunction:
    Description: "Text Lambda Function ARN"
    Value: !GetAtt ItineraryTextFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
